export const APP = {
  id: 'bd356bbe-4861-4a8b-8b4f-de64999702e7',
  name: 'Favorito',
  slug: 'favorito',
  defaultDomain: 'dev.adv.sh',
  androidUrl: 'https://play.google.com/store/apps/details?id=com.quebarbada.quebarbada',
  iosUrl: 'https://apps.apple.com/app/id1598991618',
  defaultFallbackUrl: 'https://favorito.digital',
  qrCodeLogoUrl:
    'https://kapvevgxxfwlrllswrpe.supabase.co/storage/v1/object/public/qrcode-logos/241124200422268-favorito.png',
}

export const LINKS = [
  { name: 'Black Friday 2024', slug: 'black-friday-2024' },
  { name: 'Promoção Natal App', slug: 'promocao-natal-app' },
  { name: 'Lançamento App Fitness', slug: 'lancamento-app' },
  { name: 'Ação Influenciadores Maio', slug: 'acao-influenc-maio' },
  { name: 'Desconto Exclusivo WhatsApp', slug: 'desconto-whatsapp' },
  { name: 'Campanha Afiliados Q1', slug: 'afiliados-q1' },
  { name: 'Sorteio Aniversário 2024', slug: 'sorteio-2024' },
  { name: 'QR Code Outdoor Shopping', slug: 'qr-outdoor-shop' },
  { name: 'Push Notification Junho', slug: 'push-notif-junho' },
  { name: 'Web to App Julho', slug: 'web-to-app-julho' },
  { name: 'Semana de Descontos', slug: 'semana-descontos' },
  { name: 'Instalação via SMS Agosto', slug: 'sms-agosto' },
  { name: 'Promoção Relâmpago TV', slug: 'relampago-tv' },
  { name: 'Mídia Impressa Revista', slug: 'midia-revista' },
  { name: 'Cashback Exclusivo Setembro', slug: 'cashback-setembro' },
  { name: 'Parceria Afiliados Outubro', slug: 'afiliados-outubro' },
  { name: 'Dia das Crianças Promoção', slug: 'criancas-promocao' },
  { name: 'Campanha Influencers Black Friday', slug: 'influencers-bf' },
  { name: 'Campanha Especial Influenciadores', slug: 'camp-especial-inf' },
  { name: 'E-mail Marketing Lançamento App', slug: 'email-marketing' },
  { name: 'QR Code Evento', slug: 'qr-evento' },
  { name: 'QR Code Ação Academia', slug: 'qr-acao-academia' },
  { name: 'Instalação via Anúncio TV', slug: 'anuncio-tv' },
  { name: 'Links Push Black Friday', slug: 'push-bf' },
  { name: 'Ação Influencers Novembro', slug: 'influencers-nov' },
  { name: 'Ação Outdoor Novembro', slug: 'outdoor-novembro' },
  { name: 'Retargeting Dezembro', slug: 'retargeting-dez' },
  { name: 'Instalação via WhatsApp', slug: 'instalacao-whats' },
  { name: 'Promoção de Verão', slug: 'promocao-verao' },
  { name: 'Campanha Facebook Ads Dezembro', slug: 'facebook-ads-dez' },
  { name: 'Mídia Impressa Jornal', slug: 'midia-jornal' },
  { name: 'Influenciadores Fitness 2024', slug: 'inf-fitness-2024' },
  { name: 'Instalação via QR Code Academia', slug: 'qr-academia' },
  { name: 'Retargeting Maio 2024', slug: 'retargeting-maio' },
  { name: 'Influenciadores Tecnologia Outubro', slug: 'tec-outubro' },
  { name: 'Anúncio TV Natal', slug: 'anuncio-natal' },
  { name: 'Campanha Outdoor Outubro', slug: 'outdoor-outubro' },
  { name: 'Ação Push Carnaval 2024', slug: 'push-carnaval-24' },
  { name: 'Campanha Afiliados Primavera', slug: 'afiliados-prim' },
  { name: 'E-mail Marketing Fevereiro', slug: 'email-fevereiro' },
  { name: 'Influenciadores Verão', slug: 'inf-verao' },
  { name: 'Instalação via SMS Promoção Natal', slug: 'sms-natal' },
  { name: 'E-mail Marketing Outono', slug: 'email-outono' },
  { name: 'QR Code Loja Física Novembro', slug: 'qr-loja-nov' },
  { name: 'Instalação via Notificações Push', slug: 'push-notificacoes' },
  { name: 'Web to App Aniversário 2024', slug: 'web-app-aniv-2024' },
  { name: 'QR Code TV Show', slug: 'qr-tv-show' },
  { name: 'Influenciadores Moda 2024', slug: 'inf-moda-2024' },
  { name: 'Instalação via SMS Janeiro', slug: 'sms-janeiro' },
  { name: 'Retargeting Black Friday 2023', slug: 'retargeting-bf' },
  { name: 'Campanha Afiliados Carnaval 2024', slug: 'afiliados-carnaval' },
  { name: 'Promoção Mídia Impressa Verão', slug: 'midia-verao' },
  { name: 'Instalação via Anúncio TV Inverno', slug: 'tv-inverno' },
  { name: 'Influenciadores Games 2024', slug: 'inf-games-2024' },
  { name: 'Ação Outdoor Shopping Novembro', slug: 'outdoor-shop-nov' },
  { name: 'Ação Influencers Fashion Week', slug: 'inf-fashion-week' },
  { name: 'Anúncio TV Inverno 2024', slug: 'tv-inverno-24' },
  { name: 'Influenciadores Beleza 2024', slug: 'inf-beleza-2024' },
  { name: 'Instalação via QR Code Loja Física', slug: 'qr-loja' },
  { name: 'QR Code Mídia Impressa Julho', slug: 'qr-midia-julho' },
  { name: 'Instalação via WhatsApp Verão', slug: 'whatsapp-verao' },
  { name: 'Campanha Afiliados Outono', slug: 'afiliados-outono' },
  { name: 'Campanha Influenciadores TV', slug: 'inf-tv' },
  { name: 'Web to App Julho 2024', slug: 'web-julho-24' },
  { name: 'Instalação via SMS Outubro 2024', slug: 'sms-outubro' },
  { name: 'Retargeting E-commerce', slug: 'retargeting-ecom' },
  { name: 'Push Notification Novembro 2024', slug: 'push-nov-24' },
  { name: 'Campanha Afiliados Inverno 2024', slug: 'afiliados-inverno25' },
  { name: 'Instalação via Notificações Push Outono', slug: 'push-outono' },
  { name: 'QR Code Evento Fitness', slug: 'qr-evento-fit' },
  { name: 'Instalação via WhatsApp Setembro', slug: 'whatsapp-set' },
  { name: 'Promoção de Férias Julho', slug: 'prom-ferias-julho' },
  { name: 'Mídia Impressa Outdoor Maio', slug: 'midia-maio' },
  { name: 'Campanha Afiliados Verão', slug: 'afiliados-verao' },
  { name: 'Instalação via SMS Setembro 2024', slug: 'sms-set-24' },
  { name: 'Instalação via QR Code Fevereiro', slug: 'qr-fevereiro' },
  { name: 'Influenciadores Beleza Inverno', slug: 'inf-beleza-inv' },
  { name: 'Anúncio TV Outono', slug: 'tv-outono' },
  { name: 'Web to App Outubro 2024', slug: 'web-out-24' },
  { name: 'Instalação via WhatsApp Primavera', slug: 'whatsapp-prim' },
  { name: 'Influenciadores Games Natal', slug: 'inf-games-natal' },
  { name: 'Campanha Afiliados E-commerce', slug: 'afiliados-ecom' },
  { name: 'Instalação via Notificações Push Novembro', slug: 'push-nov' },
  { name: 'E-mail Marketing Julho 2024', slug: 'email-julho-24' },
  { name: 'QR Code Fitness App', slug: 'qr-fitness-app' },
  { name: 'Influenciadores Moda Verão', slug: 'inf-moda-verao' },
  { name: 'Retargeting Inverno 2024', slug: 'retargeting-inv24' },
  { name: 'Instalação via SMS Inverno 2024', slug: 'sms-inverno24' },
  { name: 'Influenciadores Tecnologia Janeiro', slug: 'inf-tec-janeiro' },
  { name: 'QR Code Ação Inverno', slug: 'qr-acao-inv' },
  { name: 'Instalação via QR Code E-commerce', slug: 'qr-ecommerce' },
  { name: 'Ação Outdoor Verão 2024', slug: 'outdoor-verao24' },
  { name: 'Instalação via WhatsApp Novembro', slug: 'whatsapp-nov' },
  { name: 'Campanha Influencers Fitness Novembro', slug: 'inf-fit-nov' },
  { name: 'Mídia Impressa Shopping Setembro', slug: 'midia-set' },
  { name: 'Influenciadores Fitness Fevereiro', slug: 'inf-fit-fev' },
  { name: 'Retargeting Primavera', slug: 'retarget-prim' },
  { name: 'Instalação via SMS Abril 2024', slug: 'sms-abril-24' },
  { name: 'Instalação via QR Code Revista', slug: 'qr-revista' },
  { name: 'Campanha Afiliados Inverno', slug: 'afiliados-inv' },
]
